HAI 1.2
    I HAS A TOTL ITZ 0
    I HAS A NUM1 ITZ 1
    I HAS A NUM2 ITZ 1
    I HAS A NUM3 ITZ 0
    IM IN YR LOOP UPPIN YR POOP WILE BOTH SAEM BIGGR OF NUM2 AN 1000000 AN 1000000
        NUM3 R NUM1
        NUM1 R NUM2
        NUM2 R SUM OF NUM2 AN NUM3
        BOTH SAEM MOD OF NUM2 AN 2 AN 0, O RLY?
        YA RLY
            TOTL R SUM OF TOTL AN NUM2
        OIC
    IM OUTTA YR LOOP
    VISIBLE TOTL
KTHXBYE
